#!/bin/bash

#Create certificate first:

openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./tls.key -out ./tls.crt -subj "/CN=*.example.com"

#Create a TLS certificate:

openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./tls.key -out ./tls.crt -subj "/CN=*.example.com"

#Create a secret object:

kubectl create ns traefik

kubectl create secret tls traefik-ui-tls-cert --key ./tls.key --cert ./tls.crt -n traefik